{% set version = "2.3.0" %}

package:
  name: tensorflow-estimator
  version: {{ version }}

source:
  url: https://pypi.io/packages/py2.py3/t/tensorflow-estimator/tensorflow_estimator-{{ version }}-py2.py3-none-any.whl
  sha256: b75e034300ccb169403cf2695adf3368da68863aeb0c14c3760064c713d5c486

build:
  number: 0
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed tensorflow_estimator-{{ version }}-py2.py3-none-any.whl

requirements:
  build:
    - python
    - pip
  run:
    - python
    - absl-py >=0.7.0
    - astor >=0.6.0
    - gast >=0.3.3
    - numpy >=1.16.1,<1.19.0
    - six >=1.12.0
    - protobuf >=3.9.2
    - termcolor >=1.1.0
    - wrapt >=1.11.1
    - grpcio >=1.8.6

test:
  imports:
    # ImportError: /lib64/libc.so.6: version `GLIBC_2.17' not found
    - numpy

about:
  home: https://github.com/tensorflow/estimator
  license: Apache-2.0
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: TensorFlow Estimator is a high-level TensorFlow API that greatly simplifies machine learning programming.

extra:
  recipe-maintainers:
    - sdvillal
    - gilbertfrancois
    - farhantejani
    - kyleabeauchamp
    - jjhelmus
    - waitingkuo
    - ghego
    - hajapy
    - dhirschfeld
    - jschueller
